{"name": "test_create_routine", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable", "trace": "login_token = {'accessToken': 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MiIsImV4cCI6MTcxNzk0NjMxOCwicm9sZXMiOlsiVVNFUiJdLCJlbWFpbCI6InNoaW5h...GciOiJIUzI1NiJ9.eyJzdWIiOiI1MiIsImV4cCI6MTcyMDUzNzcxOH0.MG8sKakycwo6GPgT680xzvvNXvlvAyF4e8TAd_FStM4', 'type': 'Bearer'}\n\n    @allure.feature('Routine')\n    @allure.story('Create routine')\n    def test_create_routine(login_token):\n        with allure.step('Create Routine'):\n            headers = {\n>               \"Authorization\": f\"Bearer {login_token()['accessToken']}\",\n                \"Accept\": \"*/*\",\n            }\nE           TypeError: 'dict' object is not callable\n\ntests/test_routine.py:38: TypeError"}, "steps": [{"name": "Create Routine", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable\n", "trace": "  File \"/Users/alya/shit/tmm/tests/test_routine.py\", line 38, in test_create_routine\n    \"Authorization\": f\"Bearer {login_token()['accessToken']}\",\n                               ^^^^^^^^^^^^^\n"}, "start": 1717945718114, "stop": 1717945718114}], "start": 1717945718114, "stop": 1717945718114, "uuid": "7c0b7899-7532-4ee7-a7d6-0f9e5ffbec2c", "historyId": "61f850af932a5aa3edb59fb8ab665e10", "testCaseId": "61f850af932a5aa3edb59fb8ab665e10", "fullName": "tests.test_routine#test_create_routine", "labels": [{"name": "story", "value": "Create routine"}, {"name": "feature", "value": "Routine"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_routine"}, {"name": "host", "value": "Air-makbuk.Dlink"}, {"name": "thread", "value": "50615-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_routine"}]}